import type { RoleTitleSuggestion } from './role-title-suggestions.types'
import { mc2OverlayRole } from './role-title-suggestions-mc2-overlay.helpers'

export const mc2DesignRoleTitleSuggestions: RoleTitleSuggestion[] = [
  mc2OverlayRole({
    id: 'ux-ui-designer',
    department: 'design',
    group: 'product-management',
    seniority: 'individual_contributor',
    labels: { ru: 'Дизайнер интерфейсов (UX/UI)', en: 'UX/UI Designer' },
    aliases: { ru: ['дизайнер интерфейсов', 'ui ux designer'], en: ['ui designer', 'ux designer'] },
    keywords: { ru: ['интерфейс', 'макет'], en: ['interface', 'wireframe'] },
    popularityRank: 11,
    localePriority: { ru: 3, en: 18 },
  }),
  mc2OverlayRole({
    id: 'product-designer',
    department: 'design',
    group: 'product-management',
    seniority: 'individual_contributor',
    labels: { ru: 'Продуктовый дизайнер', en: 'Product Designer' },
    aliases: { ru: ['продуктовый дизайнер', 'дизайнер продукта'], en: ['ux ui designer'] },
    keywords: { ru: ['прототип', 'ux'], en: ['prototype', 'ux'] },
    popularityRank: 22,
    localePriority: { ru: 19, en: 17 },
  }),
  mc2OverlayRole({
    id: 'ux-researcher',
    department: 'design',
    group: 'product-management',
    seniority: 'individual_contributor',
    labels: { ru: 'Исследователь пользовательского опыта (UX)', en: 'UX Researcher' },
    aliases: { ru: ['исследователь пользователей', 'ux researcher'], en: ['user researcher'] },
    keywords: { ru: ['интервью', 'исследования'], en: ['interviews', 'research'] },
    popularityRank: 45,
    localePriority: { ru: 31, en: 33 },
  }),
  mc2OverlayRole({
    id: 'brand-designer',
    department: 'design',
    group: 'content-brand',
    seniority: 'individual_contributor',
    labels: { ru: 'Бренд-дизайнер', en: 'Brand Designer' },
    aliases: { ru: ['бренд-дизайнер', 'графический дизайнер'], en: ['graphic designer'] },
    keywords: { ru: ['бренд', 'айдентика'], en: ['brand', 'identity'] },
    popularityRank: 52,
    localePriority: { ru: 38, en: 38 },
  }),
  mc2OverlayRole({
    id: 'motion-designer',
    department: 'design',
    group: 'content-brand',
    seniority: 'individual_contributor',
    labels: { ru: 'Моушн-дизайнер', en: 'Motion Designer' },
    aliases: { ru: ['моушн-дизайнер', 'аниматор'], en: ['animator'] },
    keywords: { ru: ['анимация', 'видео'], en: ['animation', 'video'] },
    popularityRank: 67,
    localePriority: { ru: 48, en: 50 },
  }),
  mc2OverlayRole({
    id: 'design-lead',
    department: 'design',
    group: 'design-leadership',
    seniority: 'lead',
    labels: { ru: 'Руководитель дизайна', en: 'Design Lead' },
    aliases: { ru: ['ведущий дизайнер', 'руководитель дизайна'], en: ['lead designer'] },
    keywords: { ru: ['дизайн-система'], en: ['design system'] },
    popularityRank: 46,
    localePriority: { ru: 35, en: 35 },
  }),
]
