import type { RoleTitleSuggestion } from './role-title-suggestions.types'
import { mc2OverlayRole } from './role-title-suggestions-mc2-overlay.helpers'

export const mc2FinanceRoleTitleSuggestions: RoleTitleSuggestion[] = [
  mc2OverlayRole({
    id: 'finance-manager',
    department: 'finance',
    group: 'finance-control',
    seniority: 'manager',
    labels: { ru: 'Финансовый менеджер', en: 'Finance Manager' },
    aliases: { ru: ['finance manager', 'финансовый контролер'], en: ['financial manager'] },
    keywords: { ru: ['бюджет', 'финансы'], en: ['budget', 'finance'] },
    popularityRank: 20,
    localePriority: { ru: 17, en: 17 },
  }),
  mc2OverlayRole({
    id: 'financial-controller',
    department: 'finance',
    group: 'finance-control',
    seniority: 'manager',
    labels: { ru: 'Финансовый контролёр', en: 'Financial Controller' },
    aliases: { ru: ['финансовый контролер', 'controller'], en: ['controller'] },
    keywords: { ru: ['контроль', 'отчетность'], en: ['controls', 'reporting'] },
    popularityRank: 37,
    localePriority: { ru: 27, en: 29 },
  }),
  mc2OverlayRole({
    id: 'accountant',
    department: 'finance',
    group: 'finance-control',
    seniority: 'individual_contributor',
    labels: { ru: 'Бухгалтер', en: 'Accountant' },
    aliases: { ru: ['accountant', 'специалист бухгалтерии'], en: ['bookkeeper'] },
    keywords: { ru: ['учет', 'налоги'], en: ['accounting', 'taxes'] },
    popularityRank: 50,
    localePriority: { ru: 28, en: 44 },
  }),
  mc2OverlayRole({
    id: 'fp-and-a-manager',
    department: 'finance',
    group: 'finance-control',
    seniority: 'manager',
    labels: { ru: 'Менеджер финансового планирования и анализа (FP&A)', en: 'FP&A Manager' },
    aliases: {
      ru: ['финансовое планирование', 'financial planning manager'],
      en: ['financial planning manager'],
    },
    acronyms: ['FP&A'],
    keywords: { ru: ['планирование', 'прогноз'], en: ['planning', 'forecasting'] },
    popularityRank: 62,
    localePriority: { ru: 47, en: 47 },
  }),
  mc2OverlayRole({
    id: 'chief-financial-officer',
    department: 'finance',
    group: 'finance-control',
    seniority: 'executive',
    labels: { ru: 'Финансовый директор', en: 'Chief Financial Officer' },
    aliases: { ru: ['cfo', 'финансовый директор'], en: ['cfo', 'finance director'] },
    acronyms: ['CFO'],
    keywords: { ru: ['финансовая стратегия'], en: ['financial strategy'] },
    popularityRank: 61,
    localePriority: { ru: 44, en: 44 },
  }),
]
