import type { RoleTitleSuggestion } from './role-title-suggestions.types'
import { mc2OverlayRole } from './role-title-suggestions-mc2-overlay.helpers'

export const mc2OperationsRoleTitleSuggestions: RoleTitleSuggestion[] = [
  mc2OverlayRole({
    id: 'project-manager',
    department: 'operations',
    group: 'business-operations',
    seniority: 'manager',
    labels: { ru: 'Руководитель проекта', en: 'Project Manager' },
    aliases: { ru: ['менеджер проекта', 'руководитель проекта'], en: ['project lead'] },
    acronyms: ['PM'],
    keywords: { ru: ['сроки', 'план проекта'], en: ['timeline', 'project plan'] },
    popularityRank: 10,
    localePriority: { ru: 10, en: 12 },
  }),
  mc2OverlayRole({
    id: 'program-manager',
    department: 'operations',
    group: 'business-operations',
    seniority: 'manager',
    labels: { ru: 'Руководитель программы', en: 'Program Manager' },
    aliases: { ru: ['менеджер программы', 'руководитель программы'], en: ['program lead'] },
    acronyms: ['PM'],
    keywords: { ru: ['портфель проектов'], en: ['program portfolio'] },
    popularityRank: 32,
    localePriority: { ru: 30, en: 28 },
  }),
  mc2OverlayRole({
    id: 'operations-manager',
    department: 'operations',
    group: 'business-operations',
    seniority: 'manager',
    labels: { ru: 'Операционный менеджер', en: 'Operations Manager' },
    aliases: { ru: ['operations manager', 'операционный руководитель'], en: ['ops manager'] },
    keywords: { ru: ['процессы', 'операции'], en: ['processes', 'operations'] },
    popularityRank: 11,
    localePriority: { ru: 8, en: 8 },
  }),
  mc2OverlayRole({
    id: 'business-analyst',
    department: 'operations',
    group: 'business-operations',
    seniority: 'individual_contributor',
    labels: { ru: 'Бизнес-аналитик', en: 'Business Analyst' },
    aliases: { ru: ['business analyst', 'системный аналитик'], en: ['systems analyst'] },
    keywords: { ru: ['требования', 'процессы'], en: ['requirements', 'processes'] },
    popularityRank: 14,
    localePriority: { ru: 11, en: 11 },
  }),
  mc2OverlayRole({
    id: 'chief-operating-officer',
    department: 'operations',
    group: 'business-operations',
    seniority: 'executive',
    labels: { ru: 'Операционный директор', en: 'Chief Operating Officer' },
    aliases: { ru: ['coo', 'операционный директор'], en: ['coo', 'operations director'] },
    acronyms: ['COO'],
    keywords: { ru: ['операционная система'], en: ['operating model'] },
    popularityRank: 47,
    localePriority: { ru: 32, en: 32 },
  }),
  mc2OverlayRole({
    id: 'process-manager',
    department: 'operations',
    group: 'business-operations',
    seniority: 'manager',
    labels: { ru: 'Менеджер процессов', en: 'Process Manager' },
    aliases: { ru: ['менеджер процессов', 'process owner'], en: ['process owner'] },
    keywords: { ru: ['регламенты', 'процессы'], en: ['process improvement'] },
    popularityRank: 58,
    localePriority: { ru: 41, en: 45 },
  }),
]
