import type { RoleTitleSuggestion } from './role-title-suggestions.types'
import { mc2OverlayRole } from './role-title-suggestions-mc2-overlay.helpers'

export const mc2EngineeringRoleTitleSuggestions: RoleTitleSuggestion[] = [
  mc2OverlayRole({
    id: 'software-engineer',
    department: 'engineering',
    group: 'software-engineering',
    seniority: 'individual_contributor',
    labels: { ru: 'Инженер-программист', en: 'Software Engineer' },
    aliases: {
      ru: ['разработчик', 'программист', 'инженер-программист'],
      en: ['developer', 'programmer'],
    },
    keywords: { ru: ['код', 'разработка'], en: ['coding', 'software development'] },
    popularityRank: 2,
    localePriority: { ru: 2, en: 2 },
  }),
  mc2OverlayRole({
    id: 'frontend-developer',
    department: 'engineering',
    group: 'software-engineering',
    seniority: 'individual_contributor',
    labels: { ru: 'Фронтенд-разработчик', en: 'Frontend Developer' },
    aliases: {
      ru: ['фронтенд-разработчик', 'frontend engineer', 'разработчик интерфейсов'],
      en: ['frontend engineer', 'front-end developer'],
    },
    keywords: { ru: ['react', 'интерфейс'], en: ['react', 'ui engineering'] },
    popularityRank: 6,
    localePriority: { ru: 4, en: 5 },
  }),
  mc2OverlayRole({
    id: 'backend-developer',
    department: 'engineering',
    group: 'software-engineering',
    seniority: 'individual_contributor',
    labels: { ru: 'Бэкенд-разработчик', en: 'Backend Developer' },
    aliases: {
      ru: ['бэкенд-разработчик', 'backend engineer', 'серверный разработчик'],
      en: ['backend engineer', 'server-side developer'],
    },
    keywords: { ru: ['api', 'сервер'], en: ['api', 'server'] },
    popularityRank: 7,
    localePriority: { ru: 5, en: 6 },
  }),
  mc2OverlayRole({
    id: 'fullstack-developer',
    department: 'engineering',
    group: 'software-engineering',
    seniority: 'individual_contributor',
    labels: { ru: 'Фулстек-разработчик', en: 'Fullstack Developer' },
    aliases: {
      ru: ['фулстек-разработчик', 'full-stack engineer'],
      en: ['full-stack engineer', 'full stack developer'],
    },
    keywords: { ru: ['frontend', 'backend'], en: ['frontend', 'backend'] },
    popularityRank: 13,
    localePriority: { ru: 7, en: 7 },
  }),
  mc2OverlayRole({
    id: 'mobile-developer',
    department: 'engineering',
    group: 'software-engineering',
    seniority: 'individual_contributor',
    labels: { ru: 'Мобильный разработчик', en: 'Mobile Developer' },
    aliases: {
      ru: ['мобильный разработчик', 'ios developer', 'android developer'],
      en: ['ios developer', 'android developer'],
    },
    keywords: { ru: ['ios', 'android'], en: ['ios', 'android'] },
    popularityRank: 41,
    localePriority: { ru: 27, en: 27 },
  }),
  mc2OverlayRole({
    id: 'qa-engineer',
    department: 'engineering',
    group: 'software-engineering',
    seniority: 'individual_contributor',
    labels: { ru: 'Инженер по тестированию', en: 'QA Engineer' },
    aliases: {
      ru: ['тестировщик', 'инженер по качеству'],
      en: ['quality assurance engineer', 'tester'],
    },
    acronyms: ['QA'],
    keywords: { ru: ['тестирование', 'качество'], en: ['testing', 'quality'] },
    popularityRank: 20,
    localePriority: { ru: 14, en: 14 },
  }),
  mc2OverlayRole({
    id: 'devops-engineer',
    department: 'engineering',
    group: 'data-platform',
    seniority: 'individual_contributor',
    labels: { ru: 'DevOps-инженер', en: 'DevOps Engineer' },
    aliases: {
      ru: ['sre', 'platform engineer', 'инженер инфраструктуры'],
      en: ['sre', 'platform engineer'],
    },
    acronyms: ['SRE'],
    keywords: { ru: ['инфраструктура', 'ci cd'], en: ['infrastructure', 'ci cd'] },
    popularityRank: 15,
    localePriority: { ru: 11, en: 11 },
  }),
  mc2OverlayRole({
    id: 'platform-engineer',
    department: 'engineering',
    group: 'data-platform',
    seniority: 'individual_contributor',
    labels: { ru: 'Инженер платформы', en: 'Platform Engineer' },
    aliases: {
      ru: ['инженер платформы', 'devops'],
      en: ['devops engineer', 'infrastructure engineer'],
    },
    keywords: { ru: ['платформа разработки'], en: ['developer platform'] },
    popularityRank: 37,
    localePriority: { ru: 26, en: 24 },
  }),
  mc2OverlayRole({
    id: 'engineering-manager',
    department: 'engineering',
    group: 'engineering-leadership',
    seniority: 'manager',
    labels: { ru: 'Руководитель инженерной команды', en: 'Engineering Manager' },
    aliases: {
      ru: ['руководитель разработки', 'менеджер инженеров'],
      en: ['software development manager'],
    },
    keywords: { ru: ['команда разработки'], en: ['engineering team'] },
    popularityRank: 14,
    localePriority: { ru: 9, en: 9 },
  }),
  mc2OverlayRole({
    id: 'tech-lead',
    department: 'engineering',
    group: 'engineering-leadership',
    seniority: 'lead',
    labels: { ru: 'Технический лидер', en: 'Tech Lead' },
    aliases: { ru: ['техлид', 'technical lead'], en: ['technical lead'] },
    keywords: { ru: ['архитектура', 'ревью кода'], en: ['architecture', 'code review'] },
    popularityRank: 19,
    localePriority: { ru: 13, en: 13 },
  }),
  mc2OverlayRole({
    id: 'solution-architect',
    department: 'engineering',
    group: 'engineering-leadership',
    seniority: 'lead',
    labels: { ru: 'Архитектор решений', en: 'Solution Architect' },
    aliases: { ru: ['архитектор решений', 'системный архитектор'], en: ['systems architect'] },
    keywords: { ru: ['архитектура решений'], en: ['solution design'] },
    popularityRank: 42,
    localePriority: { ru: 28, en: 30 },
  }),
  mc2OverlayRole({
    id: 'security-engineer',
    department: 'engineering',
    group: 'data-platform',
    seniority: 'individual_contributor',
    labels: { ru: 'Инженер по безопасности', en: 'Security Engineer' },
    aliases: {
      ru: ['инженер по безопасности', 'appsec'],
      en: ['appsec engineer', 'cybersecurity engineer'],
    },
    keywords: { ru: ['безопасность', 'уязвимости'], en: ['security', 'vulnerabilities'] },
    popularityRank: 49,
    localePriority: { ru: 34, en: 34 },
  }),
]
