import type { RoleTitleSuggestion } from './role-title-suggestions.types'
import { mc2OverlayRole } from './role-title-suggestions-mc2-overlay.helpers'

export const mc2DataRoleTitleSuggestions: RoleTitleSuggestion[] = [
  mc2OverlayRole({
    id: 'data-analyst',
    department: 'data',
    group: 'analytics',
    seniority: 'individual_contributor',
    labels: { ru: 'Аналитик данных', en: 'Data Analyst' },
    aliases: { ru: ['аналитик данных', 'bi analyst'], en: ['bi analyst', 'analytics analyst'] },
    keywords: { ru: ['дашборд', 'метрики'], en: ['dashboard', 'metrics'] },
    popularityRank: 8,
    localePriority: { ru: 6, en: 4 },
  }),
  mc2OverlayRole({
    id: 'business-intelligence-analyst',
    department: 'data',
    group: 'analytics',
    seniority: 'individual_contributor',
    labels: { ru: 'Аналитик бизнес-данных (BI)', en: 'BI Analyst' },
    aliases: {
      ru: ['бизнес-аналитик данных', 'аналитик bi'],
      en: ['business intelligence analyst'],
    },
    acronyms: ['BI'],
    keywords: { ru: ['отчеты', 'визуализация'], en: ['reports', 'visualization'] },
    popularityRank: 27,
    localePriority: { ru: 21, en: 19 },
  }),
  mc2OverlayRole({
    id: 'data-scientist',
    department: 'data',
    group: 'analytics',
    seniority: 'individual_contributor',
    labels: { ru: 'Специалист по анализу данных', en: 'Data Scientist' },
    aliases: {
      ru: ['специалист по данным', 'ml researcher'],
      en: ['machine learning scientist', 'ml scientist'],
    },
    acronyms: ['ML'],
    keywords: { ru: ['машинное обучение', 'модель'], en: ['machine learning', 'modeling'] },
    popularityRank: 18,
    localePriority: { ru: 16, en: 12 },
  }),
  mc2OverlayRole({
    id: 'data-engineer',
    department: 'data',
    group: 'data-platform',
    seniority: 'individual_contributor',
    labels: { ru: 'Инженер данных', en: 'Data Engineer' },
    aliases: { ru: ['инженер данных', 'etl engineer'], en: ['etl engineer', 'analytics engineer'] },
    keywords: { ru: ['etl', 'пайплайн данных'], en: ['etl', 'data pipeline'] },
    popularityRank: 21,
    localePriority: { ru: 17, en: 16 },
  }),
  mc2OverlayRole({
    id: 'machine-learning-engineer',
    department: 'data',
    group: 'data-platform',
    seniority: 'individual_contributor',
    labels: { ru: 'Инженер машинного обучения', en: 'Machine Learning Engineer' },
    aliases: {
      ru: ['ml engineer', 'инженер машинного обучения'],
      en: ['ml engineer', 'ai engineer'],
    },
    acronyms: ['MLE', 'ML'],
    keywords: { ru: ['mlops', 'модель'], en: ['mlops', 'model serving'] },
    popularityRank: 44,
    localePriority: { ru: 33, en: 31 },
  }),
  mc2OverlayRole({
    id: 'analytics-engineer',
    department: 'data',
    group: 'analytics',
    seniority: 'individual_contributor',
    labels: { ru: 'Инженер аналитики', en: 'Analytics Engineer' },
    aliases: {
      ru: ['инженер аналитики', 'dbt analyst'],
      en: ['dbt developer', 'data modeling engineer'],
    },
    keywords: { ru: ['модель данных'], en: ['data modeling'] },
    popularityRank: 51,
    localePriority: { ru: 36, en: 36 },
  }),
  mc2OverlayRole({
    id: 'head-of-data',
    department: 'data',
    group: 'data-platform',
    seniority: 'head',
    labels: { ru: 'Руководитель направления данных', en: 'Head of Data' },
    aliases: { ru: ['руководитель данных', 'директор по данным'], en: ['data director'] },
    keywords: { ru: ['data strategy'], en: ['data strategy'] },
    popularityRank: 55,
    localePriority: { ru: 40, en: 40 },
  }),
]
