import type { RoleTitleSuggestion } from './role-title-suggestions.types'

export const roleTitleSuggestionSourceMetadata = {
  esco: {
    version: 'v1.2.1',
    lastUpdate: '2025-12-10',
    downloadUrl: 'https://esco.ec.europa.eu/en/use-esco/download',
    csvStructureUrl:
      'https://esco.ec.europa.eu/en/about-esco/escopedia/escopedia/comma-separated-values-csv',
    attribution:
      'This service uses the ESCO classification of the European Commission. Adapted display labels and Russian fallbacks are maintained by MC2.',
    languages: [
      'ar',
      'bg',
      'cs',
      'da',
      'de',
      'el',
      'en',
      'es',
      'et',
      'fi',
      'fr',
      'ga',
      'hr',
      'hu',
      'is',
      'it',
      'lt',
      'lv',
      'mt',
      'nl',
      'no',
      'pl',
      'pt',
      'ro',
      'sk',
      'sl',
      'sv',
      'uk',
    ],
    ruFallback:
      'Russian is not an ESCO source language; Russian labels, aliases, and keywords are MC2-maintained fallback copy mapped to ESCO occupation URIs.',
  },
} as const

const escoRole = (
  suggestion: Omit<RoleTitleSuggestion, 'source'> & {
    sourceReferences: { escoUri: string }
  }
): RoleTitleSuggestion => ({
  ...suggestion,
  source: 'esco',
})

export const escoRoleTitleSuggestions: RoleTitleSuggestion[] = [
  escoRole({
    id: 'product-manager',
    department: 'product',
    group: 'product-management',
    seniority: 'individual_contributor',
    labels: { ru: 'Менеджер продукта', en: 'Product Manager' },
    aliases: { ru: ['продакт', 'менеджер продукта', 'product manager'], en: ['product lead'] },
    acronyms: ['PM'],
    keywords: { ru: ['продукт', 'роадмап', 'гипотезы'], en: ['roadmap', 'discovery'] },
    popularityRank: 1,
    localePriority: { ru: 1, en: 1 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/9f508305-80ce-4111-8722-f2c9b4a44890',
    },
  }),
  escoRole({
    id: 'software-engineer',
    department: 'engineering',
    group: 'software-engineering',
    seniority: 'individual_contributor',
    labels: { ru: 'Инженер-программист', en: 'Software Developer' },
    aliases: {
      ru: ['разработчик', 'программист', 'инженер-программист', 'software engineer'],
      en: ['software engineer', 'developer', 'programmer'],
    },
    keywords: { ru: ['код', 'разработка'], en: ['coding', 'software development'] },
    popularityRank: 2,
    localePriority: { ru: 2, en: 2 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/f2b15a0e-e65a-438a-affb-29b9d50b77d1',
    },
  }),
  escoRole({
    id: 'sales-manager',
    department: 'sales',
    group: 'account-management',
    seniority: 'manager',
    labels: { ru: 'Менеджер по продажам', en: 'Sales Manager' },
    aliases: {
      ru: ['sales manager', 'менеджер продаж', 'специалист по продажам'],
      en: ['sales lead', 'sales team manager'],
    },
    keywords: {
      ru: ['продажи', 'выручка', 'клиенты', 'воронка продаж'],
      en: ['sales', 'revenue', 'customers', 'sales pipeline'],
    },
    popularityRank: 3,
    localePriority: { ru: 2, en: 3 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/a7594892-ff23-4e2a-aedf-2f967ebca15c',
    },
  }),
  escoRole({
    id: 'qa-engineer',
    department: 'engineering',
    group: 'software-engineering',
    seniority: 'individual_contributor',
    labels: { ru: 'Инженер по качеству', en: 'Quality Engineer' },
    aliases: { ru: ['qa engineer', 'тестировщик'], en: ['qa engineer', 'test engineer'] },
    acronyms: ['QA'],
    keywords: { ru: ['качество', 'тестирование'], en: ['quality', 'testing'] },
    popularityRank: 15,
    localePriority: { ru: 13, en: 13 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/30c0943c-caa1-411d-b273-26f475971273',
    },
  }),
  escoRole({
    id: 'data-analyst',
    department: 'data',
    group: 'analytics',
    seniority: 'individual_contributor',
    labels: { ru: 'Аналитик данных', en: 'Data Analyst' },
    aliases: { ru: ['data analyst', 'аналитик'], en: ['analytics analyst'] },
    keywords: { ru: ['дашборды', 'sql'], en: ['dashboards', 'sql'] },
    popularityRank: 8,
    localePriority: { ru: 7, en: 7 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/d3edb8f8-3a06-47a0-8fb9-9b212c006aa2',
    },
  }),
  escoRole({
    id: 'data-scientist',
    department: 'data',
    group: 'analytics',
    seniority: 'individual_contributor',
    labels: { ru: 'Дата-сайентист', en: 'Data Scientist' },
    aliases: { ru: ['data scientist', 'специалист по data science'], en: ['data science'] },
    keywords: { ru: ['модели', 'ml'], en: ['models', 'machine learning'] },
    popularityRank: 18,
    localePriority: { ru: 17, en: 17 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/258e46f9-0075-4a2e-adae-1ff0477e0f30',
    },
  }),
  escoRole({
    id: 'business-intelligence-analyst',
    department: 'data',
    group: 'analytics',
    seniority: 'individual_contributor',
    labels: { ru: 'BI-аналитик', en: 'Business Intelligence Analyst' },
    aliases: {
      ru: ['bi analyst', 'аналитик bi'],
      en: ['bi analyst', 'business intelligence manager'],
    },
    acronyms: ['BI'],
    keywords: { ru: ['отчеты', 'дашборды'], en: ['reporting', 'dashboards'] },
    popularityRank: 24,
    localePriority: { ru: 19, en: 19 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/207d7b18-6540-432e-8aa6-785ed434572f',
    },
  }),
  escoRole({
    id: 'ui-designer',
    department: 'design',
    group: 'product-management',
    seniority: 'individual_contributor',
    labels: { ru: 'UI-дизайнер', en: 'User Interface Designer' },
    aliases: {
      ru: ['ui designer', 'дизайнер интерфейсов'],
      en: ['ui designer', 'interface designer'],
    },
    acronyms: ['UI'],
    keywords: { ru: ['интерфейс', 'макеты'], en: ['interface', 'screens'] },
    popularityRank: 33,
    localePriority: { ru: 27, en: 27 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/96e20037-0a25-4bf6-a25e-808d1605d890',
    },
  }),
  escoRole({
    id: 'graphic-designer',
    department: 'design',
    group: 'content-brand',
    seniority: 'individual_contributor',
    labels: { ru: 'Графический дизайнер', en: 'Graphic Designer' },
    aliases: { ru: ['graphic designer', 'дизайнер графики'], en: ['visual designer'] },
    keywords: { ru: ['визуалы', 'бренд'], en: ['visuals', 'brand'] },
    popularityRank: 41,
    localePriority: { ru: 34, en: 34 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/69bcbb0a-8d80-4ecd-b0a4-9adea2a40de2',
    },
  }),
  escoRole({
    id: 'account-executive',
    department: 'sales',
    group: 'account-management',
    seniority: 'individual_contributor',
    labels: { ru: 'Менеджер по клиентским сделкам', en: 'Sales Account Manager' },
    aliases: {
      ru: ['ae', 'менеджер по ключевым клиентам', 'account executive'],
      en: ['ae', 'account executive', 'sales executive'],
    },
    acronyms: ['AE'],
    keywords: { ru: ['клиенты', 'выручка'], en: ['customers', 'revenue'] },
    popularityRank: 16,
    localePriority: { ru: 16, en: 14 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/2eac08c2-a81a-46fc-8d75-eb0e0f3e0f6d',
    },
  }),
  escoRole({
    id: 'sales-development-representative',
    department: 'sales',
    group: 'account-management',
    seniority: 'individual_contributor',
    labels: { ru: 'Специалист по развитию продаж', en: 'Commercial Sales Representative' },
    aliases: {
      ru: ['sdr', 'специалист лидогенерации', 'sales development representative'],
      en: ['sdr', 'sales development representative', 'lead generation specialist'],
    },
    acronyms: ['SDR'],
    keywords: { ru: ['лиды', 'исходящие продажи'], en: ['leads', 'outbound'] },
    popularityRank: 25,
    localePriority: { ru: 24, en: 23 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/14031d4a-6e99-442f-b4fe-18262b6432b2',
    },
  }),
  escoRole({
    id: 'marketing-manager',
    department: 'marketing',
    group: 'growth-marketing',
    seniority: 'manager',
    labels: { ru: 'Менеджер маркетинга', en: 'Marketing Manager' },
    aliases: { ru: ['marketing manager', 'менеджер маркетинга'], en: ['growth marketing manager'] },
    keywords: { ru: ['кампании', 'лиды'], en: ['campaigns', 'leads'] },
    popularityRank: 9,
    localePriority: { ru: 9, en: 9 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/6fcf4638-e7c7-4978-9302-9a7b63a3d57c',
    },
  }),
  escoRole({
    id: 'content-manager',
    department: 'marketing',
    group: 'content-brand',
    seniority: 'manager',
    labels: { ru: 'Контент-менеджер', en: 'Web Content Manager' },
    aliases: { ru: ['content manager', 'редактор контента'], en: ['content manager'] },
    keywords: { ru: ['контент', 'редактура'], en: ['content', 'editorial'] },
    popularityRank: 32,
    localePriority: { ru: 26, en: 26 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/a74f6c51-37e5-423e-aa5b-044e98663027',
    },
  }),
  escoRole({
    id: 'brand-manager',
    department: 'marketing',
    group: 'content-brand',
    seniority: 'manager',
    labels: { ru: 'Бренд-менеджер', en: 'Brand Manager' },
    aliases: { ru: ['brand manager', 'менеджер бренда'], en: ['brand lead'] },
    keywords: { ru: ['бренд', 'позиционирование'], en: ['brand', 'positioning'] },
    popularityRank: 44,
    localePriority: { ru: 38, en: 38 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/de80bbf0-447d-4a6a-845a-fdba4e0dc30c',
    },
  }),
  escoRole({
    id: 'seo-specialist',
    department: 'marketing',
    group: 'growth-marketing',
    seniority: 'individual_contributor',
    labels: { ru: 'SEO-специалист', en: 'Search Engine Optimisation Expert' },
    aliases: {
      ru: ['seo', 'seo specialist'],
      en: ['seo specialist', 'search engine optimization expert'],
    },
    acronyms: ['SEO'],
    keywords: { ru: ['поиск', 'органический трафик'], en: ['search', 'organic traffic'] },
    popularityRank: 48,
    localePriority: { ru: 41, en: 41 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/092fdeeb-a76f-4ed2-b248-90fd6eaaffef',
    },
  }),
  escoRole({
    id: 'project-manager',
    department: 'operations',
    group: 'business-operations',
    seniority: 'manager',
    labels: { ru: 'Руководитель проекта', en: 'Project Manager' },
    aliases: { ru: ['project manager', 'pm проекта'], en: ['delivery manager'] },
    acronyms: ['PM'],
    keywords: { ru: ['план', 'сроки'], en: ['timeline', 'delivery'] },
    popularityRank: 6,
    localePriority: { ru: 6, en: 6 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/bea99fea-0383-4c63-b944-70d4799de2c5',
    },
  }),
  escoRole({
    id: 'program-manager',
    department: 'operations',
    group: 'business-operations',
    seniority: 'manager',
    labels: { ru: 'Менеджер программы', en: 'Programme Manager' },
    aliases: { ru: ['program manager', 'руководитель программы'], en: ['program manager'] },
    keywords: { ru: ['портфель проектов'], en: ['program portfolio'] },
    popularityRank: 19,
    localePriority: { ru: 14, en: 15 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/c94f3565-d987-431f-a46b-6f4e018e0bd7',
    },
  }),
  escoRole({
    id: 'operations-manager',
    department: 'operations',
    group: 'business-operations',
    seniority: 'manager',
    labels: { ru: 'Операционный менеджер', en: 'Operations Manager' },
    aliases: { ru: ['operations manager', 'операционный руководитель'], en: ['ops manager'] },
    keywords: { ru: ['процессы', 'операции'], en: ['processes', 'operations'] },
    popularityRank: 14,
    localePriority: { ru: 11, en: 12 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/c6bd511a-d966-4df9-a48e-4f800354f268',
    },
  }),
  escoRole({
    id: 'business-analyst',
    department: 'operations',
    group: 'analytics',
    seniority: 'individual_contributor',
    labels: { ru: 'Бизнес-аналитик', en: 'Business Analyst' },
    aliases: { ru: ['business analyst', 'аналитик бизнес-процессов'], en: ['process analyst'] },
    keywords: { ru: ['требования', 'процессы'], en: ['requirements', 'processes'] },
    popularityRank: 20,
    localePriority: { ru: 13, en: 16 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/60082a99-d8ef-4e84-9290-78902681b6ed',
    },
  }),
  escoRole({
    id: 'supply-chain-manager',
    department: 'operations',
    group: 'business-operations',
    seniority: 'manager',
    labels: { ru: 'Менеджер цепочки поставок', en: 'Supply Chain Manager' },
    aliases: { ru: ['supply chain manager', 'менеджер поставок'], en: ['logistics manager'] },
    keywords: { ru: ['логистика', 'поставки'], en: ['logistics', 'supply'] },
    popularityRank: 55,
    localePriority: { ru: 44, en: 44 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/aacc3918-b5d3-484b-9480-5d29aa550d74',
    },
  }),
  escoRole({
    id: 'hr-manager',
    department: 'hr',
    group: 'people-operations',
    seniority: 'manager',
    labels: { ru: 'HR-менеджер', en: 'Human Resources Officer' },
    aliases: {
      ru: ['hr manager', 'менеджер по персоналу'],
      en: ['hr manager', 'human resources manager'],
    },
    acronyms: ['HR'],
    keywords: { ru: ['персонал', 'сотрудники'], en: ['people', 'employees'] },
    popularityRank: 13,
    localePriority: { ru: 10, en: 11 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/d3e32e5e-7f24-48e3-b939-e4f800eb62fb',
    },
  }),
  escoRole({
    id: 'recruiter',
    department: 'hr',
    group: 'recruiting',
    seniority: 'individual_contributor',
    labels: { ru: 'Рекрутер', en: 'Recruitment Consultant' },
    aliases: { ru: ['recruiter', 'специалист по подбору'], en: ['recruiter'] },
    keywords: { ru: ['найм', 'кандидаты'], en: ['hiring', 'candidates'] },
    popularityRank: 27,
    localePriority: { ru: 21, en: 21 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/068370e0-9c27-4814-87d0-44fbb3140815',
    },
  }),
  escoRole({
    id: 'learning-development-manager',
    department: 'hr',
    group: 'people-operations',
    seniority: 'manager',
    labels: { ru: 'Менеджер обучения и развития', en: 'Corporate Training Manager' },
    aliases: {
      ru: ['l&d', 'менеджер обучения'],
      en: ['learning and development manager', 'l&d manager'],
    },
    acronyms: ['L&D'],
    keywords: { ru: ['обучение', 'развитие'], en: ['training', 'development'] },
    popularityRank: 45,
    localePriority: { ru: 36, en: 36 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/a14e96a7-6c4d-4d69-8c6f-7ccadf77bac5',
    },
  }),
  escoRole({
    id: 'financial-analyst',
    department: 'finance',
    group: 'analytics',
    seniority: 'individual_contributor',
    labels: { ru: 'Финансовый аналитик', en: 'Financial Analyst' },
    aliases: { ru: ['financial analyst', 'аналитик финансов'], en: ['finance analyst'] },
    keywords: { ru: ['финмодель', 'бюджет'], en: ['budget', 'modeling'] },
    popularityRank: 30,
    localePriority: { ru: 22, en: 24 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/8d586ee9-0ab1-4155-a3b0-2ca786c8e48c',
    },
  }),
  escoRole({
    id: 'accountant',
    department: 'finance',
    group: 'finance-control',
    seniority: 'individual_contributor',
    labels: { ru: 'Бухгалтер', en: 'Accountant' },
    aliases: { ru: ['accountant', 'специалист бухгалтерии'], en: ['bookkeeper'] },
    keywords: { ru: ['учет', 'налоги'], en: ['accounting', 'tax'] },
    popularityRank: 42,
    localePriority: { ru: 31, en: 31 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/eda0d957-3c3c-4139-b89a-a18bc9e18897',
    },
  }),
  escoRole({
    id: 'finance-manager',
    department: 'finance',
    group: 'finance-control',
    seniority: 'manager',
    labels: { ru: 'Финансовый менеджер', en: 'Financial Manager' },
    aliases: { ru: ['finance manager', 'менеджер финансов'], en: ['finance manager'] },
    keywords: { ru: ['бюджет', 'финансы'], en: ['budgeting', 'finance'] },
    popularityRank: 40,
    localePriority: { ru: 33, en: 33 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/30f3ea93-882a-4525-841c-1d5b4b64076f',
    },
  }),
  escoRole({
    id: 'financial-controller',
    department: 'finance',
    group: 'finance-control',
    seniority: 'manager',
    labels: { ru: 'Финансовый контролер', en: 'Financial Controller' },
    aliases: { ru: ['controller', 'финансовый контроль'], en: ['controller'] },
    keywords: { ru: ['контроль', 'отчетность'], en: ['controls', 'reporting'] },
    popularityRank: 50,
    localePriority: { ru: 40, en: 40 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/5e5b1b61-1351-4d3b-a293-deb3661715dd',
    },
  }),
  escoRole({
    id: 'legal-counsel',
    department: 'legal',
    group: 'legal-compliance',
    seniority: 'individual_contributor',
    labels: { ru: 'Юрисконсульт', en: 'Corporate Lawyer' },
    aliases: { ru: ['юрист', 'legal counsel'], en: ['legal counsel', 'lawyer'] },
    keywords: { ru: ['право', 'договоры'], en: ['legal', 'contracts'] },
    popularityRank: 58,
    localePriority: { ru: 45, en: 45 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/fdfce14e-992d-4ff4-9f9d-7a353c75654e',
    },
  }),
  escoRole({
    id: 'compliance-manager',
    department: 'legal',
    group: 'legal-compliance',
    seniority: 'manager',
    labels: { ru: 'Менеджер по соблюдению требований', en: 'Regulatory Affairs Manager' },
    aliases: { ru: ['комплаенс-менеджер', 'compliance manager'], en: ['compliance manager'] },
    keywords: { ru: ['регуляторика', 'комплаенс'], en: ['regulation', 'compliance'] },
    popularityRank: 64,
    localePriority: { ru: 48, en: 48 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/779d13be-60b4-48f3-a339-fe483be96c7f',
    },
  }),
]
