import type { RoleTitleSuggestion } from './role-title-suggestions.types'
import { mc2OverlayRole } from './role-title-suggestions-mc2-overlay.helpers'

export const mc2SalesRoleTitleSuggestions: RoleTitleSuggestion[] = [
  mc2OverlayRole({
    id: 'sales-manager',
    department: 'sales',
    group: 'account-management',
    seniority: 'manager',
    labels: { ru: 'Менеджер по продажам', en: 'Sales Manager' },
    aliases: {
      ru: ['sales manager', 'менеджер продаж', 'специалист по продажам'],
      en: ['sales lead', 'sales team manager'],
    },
    keywords: {
      ru: ['продажи', 'выручка', 'клиенты', 'воронка продаж'],
      en: ['sales', 'revenue', 'customers', 'sales pipeline'],
    },
    popularityRank: 3,
    localePriority: { ru: 2, en: 3 },
    sourceReferences: {
      escoUri: 'http://data.europa.eu/esco/occupation/a7594892-ff23-4e2a-aedf-2f967ebca15c',
    },
  }),
  mc2OverlayRole({
    id: 'b2b-sales-manager',
    department: 'sales',
    group: 'account-management',
    seniority: 'manager',
    labels: { ru: 'Менеджер по корпоративным продажам (B2B)', en: 'B2B Sales Manager' },
    aliases: {
      ru: ['sales manager b2b', 'менеджер b2b продаж', 'менеджер по продажам для бизнеса'],
      en: ['b2b account manager', 'business sales manager'],
    },
    keywords: { ru: ['воронка продаж', 'сделки'], en: ['sales pipeline', 'deals'] },
    popularityRank: 4,
    localePriority: { ru: 4, en: 4 },
  }),
  mc2OverlayRole({
    id: 'b2c-sales-manager',
    department: 'sales',
    group: 'account-management',
    seniority: 'manager',
    labels: { ru: 'Менеджер по продажам частным клиентам (B2C)', en: 'B2C Sales Manager' },
    aliases: {
      ru: ['sales manager b2c', 'менеджер b2c продаж', 'менеджер по продажам частным клиентам'],
      en: ['consumer sales manager', 'direct sales manager'],
    },
    keywords: {
      ru: ['b2c', 'частные клиенты', 'розница', 'прямые продажи'],
      en: ['b2c', 'consumer sales', 'direct sales'],
    },
    popularityRank: 21,
    localePriority: { ru: 5, en: 20 },
  }),
  mc2OverlayRole({
    id: 'retail-sales-manager',
    department: 'sales',
    group: 'account-management',
    seniority: 'manager',
    labels: { ru: 'Менеджер розничных продаж', en: 'Retail Sales Manager' },
    aliases: {
      ru: ['retail sales manager', 'менеджер по продажам в рознице', 'менеджер розницы'],
      en: ['retail manager', 'shop sales manager'],
    },
    keywords: { ru: ['розница', 'магазин', 'b2c'], en: ['retail', 'store', 'b2c'] },
    popularityRank: 22,
    localePriority: { ru: 6, en: 21 },
  }),
  mc2OverlayRole({
    id: 'head-of-sales',
    department: 'sales',
    group: 'commercial-leadership',
    seniority: 'head',
    labels: { ru: 'Руководитель отдела продаж', en: 'Head of Sales' },
    aliases: {
      ru: ['директор по продажам', 'head of sales', 'sales director'],
      en: ['sales director', 'vp sales'],
    },
    keywords: { ru: ['команда продаж'], en: ['sales team'] },
    popularityRank: 4,
    localePriority: { ru: 1, en: 4 },
  }),
  mc2OverlayRole({
    id: 'account-executive',
    department: 'sales',
    group: 'account-management',
    seniority: 'individual_contributor',
    labels: { ru: 'Менеджер по клиентским сделкам', en: 'Account Executive' },
    aliases: { ru: ['ae', 'менеджер по ключевым клиентам'], en: ['ae', 'sales executive'] },
    acronyms: ['AE'],
    keywords: { ru: ['клиенты', 'выручка'], en: ['customers', 'revenue'] },
    popularityRank: 16,
    localePriority: { ru: 16, en: 14 },
  }),
  mc2OverlayRole({
    id: 'sales-development-representative',
    department: 'sales',
    group: 'account-management',
    seniority: 'individual_contributor',
    labels: { ru: 'Специалист по развитию продаж', en: 'Sales Development Representative' },
    aliases: { ru: ['sdr', 'специалист лидогенерации'], en: ['sdr', 'lead generation specialist'] },
    acronyms: ['SDR'],
    keywords: { ru: ['лиды', 'исходящие продажи'], en: ['leads', 'outbound'] },
    popularityRank: 25,
    localePriority: { ru: 24, en: 23 },
  }),
  mc2OverlayRole({
    id: 'key-account-manager',
    department: 'sales',
    group: 'account-management',
    seniority: 'manager',
    labels: { ru: 'Менеджер по ключевым клиентам', en: 'Key Account Manager' },
    aliases: {
      ru: ['кам', 'менеджер ключевых клиентов'],
      en: ['kam', 'strategic account manager'],
    },
    acronyms: ['KAM'],
    keywords: { ru: ['ключевые клиенты'], en: ['key accounts'] },
    popularityRank: 28,
    localePriority: { ru: 23, en: 25 },
  }),
  mc2OverlayRole({
    id: 'sales-operations-manager',
    department: 'sales',
    group: 'business-operations',
    seniority: 'manager',
    labels: { ru: 'Менеджер операционных процессов продаж', en: 'Sales Operations Manager' },
    aliases: {
      ru: ['sales ops', 'менеджер операционной поддержки продаж'],
      en: ['sales ops manager'],
    },
    keywords: { ru: ['crm', 'прогноз продаж'], en: ['crm', 'sales forecast'] },
    popularityRank: 39,
    localePriority: { ru: 30, en: 29 },
  }),
  mc2OverlayRole({
    id: 'channel-sales-manager',
    department: 'sales',
    group: 'account-management',
    seniority: 'manager',
    labels: { ru: 'Менеджер партнёрских продаж', en: 'Channel Sales Manager' },
    aliases: {
      ru: ['партнерские продажи', 'channel manager', 'менеджер по продажам через партнеров'],
      en: ['partner sales manager', 'channel manager'],
    },
    keywords: { ru: ['партнеры', 'каналы'], en: ['partners', 'channels'] },
    popularityRank: 57,
    localePriority: { ru: 42, en: 42 },
  }),
  mc2OverlayRole({
    id: 'revenue-operations-manager',
    department: 'sales',
    group: 'business-operations',
    seniority: 'manager',
    labels: { ru: 'Менеджер операций выручки (RevOps)', en: 'Revenue Operations Manager' },
    aliases: { ru: ['revops', 'менеджер revenue operations'], en: ['revops manager'] },
    acronyms: ['RevOps'],
    keywords: { ru: ['выручка', 'операции продаж'], en: ['revenue', 'go-to-market operations'] },
    popularityRank: 43,
    localePriority: { ru: 39, en: 32 },
  }),
]
