import type { RoleTitleSuggestion } from './role-title-suggestions.types'
import { mc2OverlayRole } from './role-title-suggestions-mc2-overlay.helpers'

export const mc2MarketingRoleTitleSuggestions: RoleTitleSuggestion[] = [
  mc2OverlayRole({
    id: 'product-marketing-manager',
    department: 'marketing',
    group: 'content-brand',
    seniority: 'manager',
    labels: { ru: 'Менеджер продуктового маркетинга', en: 'Product Marketing Manager' },
    aliases: { ru: ['pmm', 'маркетолог продукта'], en: ['pmm', 'go-to-market manager'] },
    acronyms: ['PMM'],
    keywords: { ru: ['позиционирование', 'gtm'], en: ['positioning', 'gtm'] },
    popularityRank: 38,
    localePriority: { ru: 32, en: 28 },
  }),
  mc2OverlayRole({
    id: 'marketing-manager',
    department: 'marketing',
    group: 'growth-marketing',
    seniority: 'manager',
    labels: { ru: 'Менеджер маркетинга', en: 'Marketing Manager' },
    aliases: { ru: ['marketing manager', 'менеджер маркетинга'], en: ['growth marketing manager'] },
    keywords: { ru: ['кампании', 'лиды'], en: ['campaigns', 'leads'] },
    popularityRank: 9,
    localePriority: { ru: 9, en: 9 },
  }),
  mc2OverlayRole({
    id: 'performance-marketing-manager',
    department: 'marketing',
    group: 'growth-marketing',
    seniority: 'manager',
    labels: { ru: 'Менеджер по результативной рекламе', en: 'Performance Marketing Manager' },
    aliases: {
      ru: ['перформанс-маркетолог', 'paid ads'],
      en: ['paid marketing manager', 'ppc manager'],
    },
    keywords: { ru: ['реклама', 'cpa'], en: ['paid ads', 'cpa'] },
    popularityRank: 23,
    localePriority: { ru: 18, en: 21 },
  }),
  mc2OverlayRole({
    id: 'content-marketing-manager',
    department: 'marketing',
    group: 'content-brand',
    seniority: 'manager',
    labels: { ru: 'Менеджер контент-маркетинга', en: 'Content Marketing Manager' },
    aliases: { ru: ['контент-маркетолог', 'content manager'], en: ['content manager'] },
    keywords: { ru: ['контент', 'редакция'], en: ['content', 'editorial'] },
    popularityRank: 30,
    localePriority: { ru: 25, en: 26 },
  }),
  mc2OverlayRole({
    id: 'brand-manager',
    department: 'marketing',
    group: 'content-brand',
    seniority: 'manager',
    labels: { ru: 'Бренд-менеджер', en: 'Brand Manager' },
    aliases: { ru: ['бренд-менеджер'], en: ['brand lead'] },
    keywords: { ru: ['бренд', 'позиционирование'], en: ['brand', 'positioning'] },
    popularityRank: 40,
    localePriority: { ru: 29, en: 37 },
  }),
  mc2OverlayRole({
    id: 'growth-marketer',
    department: 'marketing',
    group: 'growth-marketing',
    seniority: 'individual_contributor',
    labels: { ru: 'Маркетолог роста', en: 'Growth Marketer' },
    aliases: { ru: ['маркетолог роста', 'growth manager'], en: ['growth manager'] },
    keywords: { ru: ['эксперименты', 'активация'], en: ['experiments', 'activation'] },
    popularityRank: 33,
    localePriority: { ru: 28, en: 24 },
  }),
  mc2OverlayRole({
    id: 'seo-specialist',
    department: 'marketing',
    group: 'growth-marketing',
    seniority: 'individual_contributor',
    labels: { ru: 'SEO-специалист', en: 'SEO Specialist' },
    aliases: { ru: ['seo-специалист', 'специалист по seo'], en: ['seo manager'] },
    acronyms: ['SEO'],
    keywords: { ru: ['органический трафик', 'поиск'], en: ['organic traffic', 'search'] },
    popularityRank: 36,
    localePriority: { ru: 27, en: 34 },
  }),
  mc2OverlayRole({
    id: 'crm-marketing-manager',
    department: 'marketing',
    group: 'growth-marketing',
    seniority: 'manager',
    labels: { ru: 'Менеджер CRM-маркетинга', en: 'CRM Marketing Manager' },
    aliases: {
      ru: ['crm-маркетолог', 'email marketing manager'],
      en: ['email marketing manager', 'lifecycle marketer'],
    },
    acronyms: ['CRM'],
    keywords: { ru: ['рассылки', 'retention'], en: ['email', 'lifecycle'] },
    popularityRank: 48,
    localePriority: { ru: 41, en: 39 },
  }),
  mc2OverlayRole({
    id: 'marketing-operations-manager',
    department: 'marketing',
    group: 'business-operations',
    seniority: 'manager',
    labels: { ru: 'Менеджер маркетинговых операций', en: 'Marketing Operations Manager' },
    aliases: { ru: ['marketing ops', 'операции маркетинга'], en: ['marketing ops manager'] },
    keywords: { ru: ['маркетинг-стек', 'атрибуция'], en: ['marketing stack', 'attribution'] },
    popularityRank: 53,
    localePriority: { ru: 43, en: 41 },
  }),
]
