import type { RoleTitleSuggestion } from './role-title-suggestions.types'
import { mc2OverlayRole } from './role-title-suggestions-mc2-overlay.helpers'

export const mc2ProductRoleTitleSuggestions: RoleTitleSuggestion[] = [
  mc2OverlayRole({
    id: 'product-manager',
    department: 'product',
    group: 'product-management',
    seniority: 'individual_contributor',
    labels: { ru: 'Менеджер продукта', en: 'Product Manager' },
    aliases: { ru: ['продакт', 'менеджер продукта', 'product manager'], en: ['product lead'] },
    acronyms: ['PM'],
    keywords: { ru: ['продукт', 'роадмап', 'гипотезы'], en: ['roadmap', 'discovery'] },
    popularityRank: 1,
    localePriority: { ru: 1, en: 1 },
  }),
  mc2OverlayRole({
    id: 'product-owner',
    department: 'product',
    group: 'product-management',
    seniority: 'individual_contributor',
    labels: { ru: 'Владелец продукта', en: 'Product Owner' },
    aliases: { ru: ['владелец продукта'], en: ['po', 'scrum product owner'] },
    acronyms: ['PO'],
    keywords: { ru: ['бэклог', 'спринт'], en: ['backlog', 'scrum'] },
    popularityRank: 12,
    localePriority: { ru: 8, en: 8 },
  }),
  mc2OverlayRole({
    id: 'head-of-product',
    department: 'product',
    group: 'product-leadership',
    seniority: 'head',
    labels: { ru: 'Руководитель продукта', en: 'Head of Product' },
    aliases: { ru: ['руководитель продукта'], en: ['product lead'] },
    keywords: { ru: ['портфель продуктов'], en: ['product portfolio'] },
    popularityRank: 17,
    localePriority: { ru: 10, en: 10 },
  }),
  mc2OverlayRole({
    id: 'chief-product-officer',
    department: 'product',
    group: 'product-leadership',
    seniority: 'executive',
    labels: { ru: 'Директор по продукту', en: 'Chief Product Officer' },
    aliases: { ru: ['cpo', 'директор по продукту'], en: ['cpo', 'vp product'] },
    acronyms: ['CPO'],
    keywords: { ru: ['продуктовая стратегия'], en: ['product strategy'] },
    popularityRank: 34,
    localePriority: { ru: 18, en: 18 },
  }),
  mc2OverlayRole({
    id: 'technical-product-manager',
    department: 'product',
    group: 'product-management',
    seniority: 'individual_contributor',
    labels: { ru: 'Технический менеджер продукта', en: 'Technical Product Manager' },
    aliases: { ru: ['технический продакт'], en: ['technical pm', 'platform product manager'] },
    acronyms: ['TPM'],
    keywords: { ru: ['api', 'платформа'], en: ['api', 'platform'] },
    popularityRank: 26,
    localePriority: { ru: 15, en: 15 },
  }),
  mc2OverlayRole({
    id: 'growth-product-manager',
    department: 'product',
    group: 'product-management',
    seniority: 'individual_contributor',
    labels: { ru: 'Менеджер продукта по росту', en: 'Growth Product Manager' },
    aliases: { ru: ['growth pm', 'продуктовый менеджер роста'], en: ['growth pm'] },
    acronyms: ['GPM'],
    keywords: { ru: ['активация', 'retention'], en: ['activation', 'retention'] },
    popularityRank: 31,
    localePriority: { ru: 20, en: 20 },
  }),
  mc2OverlayRole({
    id: 'product-analyst',
    department: 'product',
    group: 'analytics',
    seniority: 'individual_contributor',
    labels: { ru: 'Продуктовый аналитик', en: 'Product Analyst' },
    aliases: { ru: ['product analyst', 'аналитик продукта'], en: ['product analytics'] },
    keywords: { ru: ['метрики продукта', 'воронка'], en: ['product metrics', 'funnel'] },
    popularityRank: 29,
    localePriority: { ru: 12, en: 22 },
  }),
]
