import type { RoleTitleSuggestion } from './role-title-suggestions.types'
import { mc2OverlayRole } from './role-title-suggestions-mc2-overlay.helpers'

export const mc2SupportRoleTitleSuggestions: RoleTitleSuggestion[] = [
  mc2OverlayRole({
    id: 'customer-success-manager',
    department: 'support',
    group: 'customer-implementation',
    seniority: 'manager',
    labels: { ru: 'Менеджер по развитию клиентов', en: 'Customer Success Manager' },
    aliases: { ru: ['csm', 'менеджер по успеху клиентов'], en: ['csm', 'client success manager'] },
    acronyms: ['CSM'],
    keywords: { ru: ['удержание клиентов', 'аккаунты'], en: ['retention', 'accounts'] },
    popularityRank: 5,
    localePriority: { ru: 6, en: 5 },
  }),
  mc2OverlayRole({
    id: 'support-specialist',
    department: 'support',
    group: 'customer-support',
    seniority: 'individual_contributor',
    labels: { ru: 'Специалист поддержки', en: 'Support Specialist' },
    aliases: { ru: ['customer support', 'саппорт'], en: ['customer support specialist'] },
    keywords: { ru: ['тикеты', 'клиенты'], en: ['tickets', 'customers'] },
    popularityRank: 24,
    localePriority: { ru: 22, en: 20 },
  }),
  mc2OverlayRole({
    id: 'customer-support-lead',
    department: 'support',
    group: 'customer-support',
    seniority: 'lead',
    labels: { ru: 'Руководитель поддержки', en: 'Customer Support Lead' },
    aliases: { ru: ['support lead', 'лид поддержки'], en: ['support lead', 'head of support'] },
    keywords: { ru: ['sla', 'поддержка'], en: ['sla', 'support'] },
    popularityRank: 35,
    localePriority: { ru: 26, en: 31 },
  }),
  mc2OverlayRole({
    id: 'implementation-manager',
    department: 'support',
    group: 'customer-implementation',
    seniority: 'manager',
    labels: { ru: 'Менеджер внедрения', en: 'Implementation Manager' },
    aliases: { ru: ['менеджер внедрения', 'onboarding manager'], en: ['onboarding manager'] },
    keywords: {
      ru: ['внедрение', 'онбординг клиента'],
      en: ['implementation', 'customer onboarding'],
    },
    popularityRank: 50,
    localePriority: { ru: 37, en: 36 },
  }),
  mc2OverlayRole({
    id: 'technical-account-manager',
    department: 'support',
    group: 'customer-implementation',
    seniority: 'manager',
    labels: { ru: 'Технический менеджер по клиентам', en: 'Technical Account Manager' },
    aliases: { ru: ['tam', 'технический аккаунт-менеджер'], en: ['tam'] },
    acronyms: ['TAM'],
    keywords: { ru: ['техническая поддержка клиента'], en: ['technical customer success'] },
    popularityRank: 56,
    localePriority: { ru: 44, en: 43 },
  }),
]
