/**
 * OLX HTML Component Template Generator
 * @module integrations/lms/openedx/olx/templates/html
 *
 * Generates HTML component XML and content files for Open edX OLX format.
 * HTML components are the primary content delivery mechanism in Open edX courses.
 */

import { xmlEscape } from '../../utils/xml-escape';

/**
 * Generate HTML component XML reference
 *
 * Creates the XML reference file for an HTML component.
 * This file points to the actual HTML content stored separately.
 *
 * @param urlName - Component's unique URL name (ASCII identifier)
 * @param displayName - Human-readable component name (supports Cyrillic)
 * @returns XML string for html/{url_name}.xml file
 *
 * @example
 * ```typescript
 * const htmlXml = generateHtmlXml('content_1', 'Текст урока');
 * // Generates: <html url_name="content_1" display_name="Текст урока"/>
 * ```
 */
export function generateHtmlXml(urlName: string, displayName: string): string {
  return `<html url_name="${xmlEscape(urlName)}" display_name="${xmlEscape(displayName)}"/>
`;
}

/**
 * Generate HTML content file
 *
 * Wraps lesson content in proper HTML structure for Open edX.
 * The content is assumed to be trusted (generated by AI or instructor),
 * so XSS prevention is not applied.
 *
 * Open edX expects HTML components to have a basic HTML structure
 * with <html>, <head>, and <body> tags.
 *
 * @param content - HTML content to wrap (trusted, no XSS filtering)
 * @returns Complete HTML document string for html/{url_name}.html file
 *
 * @example
 * ```typescript
 * const htmlContent = generateHtmlContent('<p>Введение в ИИ</p>');
 * // Generates:
 * // <html>
 * //   <head></head>
 * //   <body>
 * //     <p>Введение в ИИ</p>
 * //   </body>
 * // </html>
 * ```
 */
export function generateHtmlContent(content: string): string {
  return `<html>
  <head></head>
  <body>
${content}
  </body>
</html>
`;
}
