/**
 * Regression tests for the quality-contract checks.
 *
 * Every positive case is taken verbatim from the representative run of
 * 2026-08-11 that scored 2.6/5 editorially
 * (packages/course-gen-platform/artifacts/career-playbook-quality/career-playbook.md,
 * line references in the assertions). Writing them against real observed output
 * rather than invented samples is the point: these checks exist because a human
 * found these exact lines, and the suite has to fail on the old output.
 */

import { describe, expect, it } from 'vitest';
import type {
  CareerPlaybookBlockId,
  CareerPlaybookBlockState,
  CareerPlaybookEvidenceEntry,
  CareerPlaybookMetricLedgerEntry,
} from '@megacampus/shared-types';
import {
  runCareerPlaybookContractChecks,
  stripFencedBlocks,
  validateAntiGoalConflict,
  validateExampleMarking,
  validateMetricLedgerConsistency,
  validateRelativeDates,
  validateUnsourcedStatistics,
  type CareerPlaybookQualityCheckContext,
} from '@/stages/stage-career-playbook/nodes/quality-checks';

function block(content: string): CareerPlaybookBlockState {
  return { content, status: 'generated', attempt: 1 };
}

function blocks(
  entries: Partial<Record<CareerPlaybookBlockId, string>>
): Partial<Record<CareerPlaybookBlockId, CareerPlaybookBlockState>> {
  return Object.fromEntries(
    Object.entries(entries).map(([blockId, content]) => [blockId, block(content as string)])
  );
}

const PIPELINE_COVERAGE: CareerPlaybookMetricLedgerEntry = {
  key: 'pipeline_coverage',
  label: 'Pipeline coverage ratio',
  unit: 'x',
  target: '>=3x',
  green: '>=3x',
  yellow: '2-2.9x',
  red: '<2x',
  review_period: 'quarter',
  provenance: 'assumption',
  source_ref: null,
};

const FORECAST_ACCURACY: CareerPlaybookMetricLedgerEntry = {
  key: 'forecast_accuracy',
  label: 'Forecast accuracy',
  unit: '%',
  target: 'within +/-10%',
  green: '>=90%',
  yellow: '80-89%',
  red: '<80%',
  review_period: 'quarter',
  provenance: 'assumption',
  source_ref: null,
};

const EVIDENCE: CareerPlaybookEvidenceEntry = {
  id: 'S1',
  url: 'https://example.com/b2b-ai-adoption',
  title: 'B2B AI adoption 2026',
  claim: 'AI assistants reach 90-95% accuracy on call summarisation',
  retrieved_at: '2026-08-11',
};

function context(
  overrides: Partial<CareerPlaybookQualityCheckContext> = {}
): CareerPlaybookQualityCheckContext {
  return {
    metricLedger: [PIPELINE_COVERAGE, FORECAST_ACCURACY],
    evidenceLedger: [],
    generatedOn: '2026-08-11',
    businessContextMode: 'universal',
    ...overrides,
  };
}

describe('stripFencedBlocks', () => {
  it('removes mermaid and code fences so diagram labels are not read as claims', () => {
    const markdown = 'text\n```mermaid\nA["3x coverage"]\n```\nmore';
    expect(stripFencedBlocks(markdown)).not.toContain('3x coverage');
    expect(stripFencedBlocks(markdown)).toContain('more');
  });
});

describe('validateMetricLedgerConsistency', () => {
  it('flags the real 2x/3x pipeline-coverage clash from career-playbook.md:46 vs :87', () => {
    // Line 46 of the reviewed output said >=2x while line 87 said >=3x, in two
    // blocks generated by the SAME prompt call.
    const issues = validateMetricLedgerConsistency(
      blocks({
        block_3: '| **Pipeline management** | 25% | Pipeline coverage ratio is at least 2x |',
      }),
      context()
    );

    expect(issues).toHaveLength(1);
    expect(issues[0].category).toBe('metric_conflict');
    expect(issues[0].block_id).toBe('block_3');
    expect(issues[0].description).toContain('Pipeline coverage ratio');
  });

  it('flags the forecast +/-5% variant while the ledger says +/-10%', () => {
    const issues = validateMetricLedgerConsistency(
      blocks({
        block_15: '| **Forecast accuracy** | 15% weight | Forecast within +/-5% of actuals |',
      }),
      context({ metricLedger: [FORECAST_ACCURACY] })
    );

    expect(issues.map(item => item.category)).toEqual(['metric_conflict']);
  });

  it('accepts a line that quotes the ledger value', () => {
    const issues = validateMetricLedgerConsistency(
      blocks({
        block_6:
          '| **Pipeline coverage ratio** | >=3x quarterly target | Green: >=3x. Yellow: 2-2.9x. Red: <2x |',
      }),
      context()
    );

    expect(issues).toEqual([]);
  });

  it('catches the shorter prose form of a metric label (career-playbook.md:710)', () => {
    // The KPI table wrote "Pipeline coverage ratio"; the FMEA table wrote
    // "pipeline coverage drops below 4x". Exact-label matching missed it.
    const issues = validateMetricLedgerConsistency(
      blocks({ block_21: '| Impact | 3+ deals at risk; pipeline coverage drops below 4x | |' }),
      context({ metricLedger: [PIPELINE_COVERAGE] })
    );

    expect(issues.map(item => item.category)).toEqual(['metric_conflict']);
  });

  it('does nothing when the ledger is empty, so legacy specs still judge cleanly', () => {
    const issues = validateMetricLedgerConsistency(
      blocks({ block_3: 'Pipeline coverage ratio is at least 2x' }),
      context({ metricLedger: [] })
    );

    expect(issues).toEqual([]);
  });
});

describe('validateUnsourcedStatistics', () => {
  it('flags the real "90-95% accuracy" AI claim from career-playbook.md:154', () => {
    const issues = validateUnsourcedStatistics(
      blocks({
        block_9:
          'Repetitive tasks where research shows AI delivers 90-95% accuracy and frees manager time.',
      }),
      context()
    );

    expect(issues).toHaveLength(1);
    expect(issues[0].category).toBe('unsourced_claim');
  });

  it('flags the real "95% weekly / 65% daily" adoption claim from career-playbook.md:805', () => {
    const issues = validateUnsourcedStatistics(
      blocks({
        block_19:
          'B2B SaaS industry data: 95% of B2B marketers use AI weekly, and 65% use it daily.',
      }),
      context()
    );

    expect(issues.map(item => item.category)).toEqual(['unsourced_claim']);
  });

  it('ignores internal statements that merely sound like research', () => {
    // The first version of this check flagged all three of these, which would
    // have spent paid regenerations on correct content.
    const issues = validateUnsourcedStatistics(
      blocks({
        block_15:
          '| Retention | 10% | Voluntary turnover under target | Based on pulse survey results |',
        block_3:
          '| Process optimization | 5% | One improvement per quarter; team adoption tracked |',
        block_21:
          'Engagement scores consistently below company benchmark; fewer than 80 % of 1:1s happen.',
      }),
      context()
    );

    expect(issues).toEqual([]);
  });

  it('ignores a line stating one of the role own ledger metrics', () => {
    const issues = validateUnsourcedStatistics(
      blocks({ block_6: 'Market-facing Pipeline coverage ratio target is >=3x each quarter.' }),
      context()
    );

    expect(issues).toEqual([]);
  });

  it('accepts the same claim once it carries a resolvable citation', () => {
    const issues = validateUnsourcedStatistics(
      blocks({
        block_9: 'Research shows AI delivers 90-95% accuracy on call summarisation [S1].',
      }),
      context({ evidenceLedger: [EVIDENCE] })
    );

    expect(issues).toEqual([]);
  });

  it('flags a citation that resolves to nothing', () => {
    const issues = validateUnsourcedStatistics(
      blocks({ block_9: 'Industry benchmarks put adoption at 65% [S7].' }),
      context({ evidenceLedger: [EVIDENCE] })
    );

    expect(issues).toHaveLength(1);
    expect(issues[0].description).toContain('[S7]');
  });
});

describe('validateExampleMarking', () => {
  it('flags the real $120,000/$60,000 compensation split from career-playbook.md:500-506', () => {
    const issues = validateExampleMarking(
      blocks({ block_15: '| Base salary | $120,000 | On-target commission $60,000 |' }),
      context()
    );

    expect(issues).toHaveLength(1);
    expect(issues[0].category).toBe('unmarked_example');
  });

  it('flags the real $50M incremental ARR scenario from career-playbook.md:843', () => {
    const issues = validateExampleMarking(
      blocks({ block_20: 'A $50M incremental ARR scenario depends on this role.' }),
      context()
    );

    expect(issues).toHaveLength(1);
  });

  it('accepts the same value once marked as replaceable', () => {
    const issues = validateExampleMarking(
      blocks({ block_15: '| Base salary | $120,000 (example — replace) | |' }),
      context()
    );

    expect(issues).toEqual([]);
  });

  it('stays silent in company_specific mode, where real figures are legitimate', () => {
    const issues = validateExampleMarking(
      blocks({ block_15: '| Base salary | $120,000 | |' }),
      context({ businessContextMode: 'company_specific' })
    );

    expect(issues).toEqual([]);
  });
});

describe('validateRelativeDates', () => {
  it('flags the real January-March 2025 onboarding Gantt from career-playbook.md:393-425', () => {
    const issues = validateRelativeDates(
      blocks({ block_14: '| Week 1 | January 2025 | Shadow calls |' }),
      context()
    );

    expect(issues).toHaveLength(1);
    expect(issues[0].category).toBe('stale_date');
    expect(issues[0].description).toContain('2025');
  });

  it('accepts relative labels', () => {
    const issues = validateRelativeDates(
      blocks({ block_14: '| Week 1 | Day 1-7 | Shadow calls |' }),
      context()
    );

    expect(issues).toEqual([]);
  });

  it('allows the generation year in the footer block', () => {
    const issues = validateRelativeDates(
      blocks({ block_25: 'Version 1.0, 2026-08-11.' }),
      context()
    );

    expect(issues).toEqual([]);
  });

  it('skips entirely when the spec carries no generation date', () => {
    const issues = validateRelativeDates(
      blocks({ block_14: 'January 2025' }),
      context({ generatedOn: undefined })
    );

    expect(issues).toEqual([]);
  });
});

describe('validateAntiGoalConflict', () => {
  const antiGoal =
    '## 2. Anti-goals\n\n| Do not micromanage individual activity | Undermines ownership | Sales Manager |';

  it('flags the real per-report daily review from career-playbook.md:55-56', () => {
    const issues = validateAntiGoalConflict(
      blocks({
        block_2: antiGoal,
        block_4: '| **Daily** | Review one recorded call per rep | Coaching note logged |',
      }),
      context()
    );

    expect(issues).toHaveLength(1);
    expect(issues[0].category).toBe('contradiction');
    expect(issues[0].block_id).toBe('block_4');
  });

  it('accepts a sampled cadence that respects the anti-goal', () => {
    const issues = validateAntiGoalConflict(
      blocks({
        block_2: antiGoal,
        block_4:
          '| **Weekly** | Review a sample of recorded calls across the team | Coaching note logged |',
      }),
      context()
    );

    expect(issues).toEqual([]);
  });

  it('stays silent when no micromanagement anti-goal was published', () => {
    const issues = validateAntiGoalConflict(
      blocks({
        block_2: '## 2. Anti-goals\n\n| Do not own marketing budget | Wrong scope | CMO |',
        block_4: '| **Daily** | Review one recorded call per rep | Note |',
      }),
      context()
    );

    expect(issues).toEqual([]);
  });
});

describe('runCareerPlaybookContractChecks', () => {
  it('reports every contract violation present in the reviewed output at once', () => {
    const issues = runCareerPlaybookContractChecks(
      blocks({
        block_2: '## 2. Anti-goals\n\n| Do not micromanage individual activity | x | y |',
        block_3: 'Pipeline coverage ratio is at least 2x',
        block_4: '| **Daily** | Review one recorded call per rep | Note |',
        block_9: 'Research shows AI delivers 90-95% accuracy.',
        block_14: '| Week 1 | January 2025 | Shadow calls |',
        block_15: '| Base salary | $120,000 | |',
      }),
      context()
    );

    expect(new Set(issues.map(item => item.category))).toEqual(
      new Set([
        'metric_conflict',
        'unsourced_claim',
        'unmarked_example',
        'stale_date',
        'contradiction',
      ])
    );
    expect(issues.every(item => item.severity === 'critical')).toBe(true);
  });

  it('returns nothing for output that satisfies the contract', () => {
    const issues = runCareerPlaybookContractChecks(
      blocks({
        block_2: '## 2. Anti-goals\n\n| Do not micromanage individual activity | x | y |',
        block_6: '| **Pipeline coverage ratio** | >=3x | Green: >=3x. Yellow: 2-2.9x. Red: <2x |',
        block_9: 'Research shows AI delivers 90-95% accuracy [S1].',
        block_14: '| Week 1 | Day 1-7 | Shadow calls |',
        block_15: '| Base salary | $120,000 (example — replace) | |',
      }),
      context({ evidenceLedger: [EVIDENCE] })
    );

    expect(issues).toEqual([]);
  });
});
