/**
 * Contract: an image edit refreshes the course total, exactly like a token call.
 *
 * `recordLlmCallCost` ends by scheduling the re-sum; `recordImageCallCost` did
 * not. Nothing was losing money over it today — every image comes from stage 7,
 * whose job refreshes the total when it finishes — but the asymmetry was the
 * trap, not the symptom: the first edit path to generate an image would write
 * its trace row and leave `courses.estimated_cost_usd` untouched, which is the
 * silent-zero shape this whole feature exists to remove (mc2-6kmfx).
 */

import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

const { logTrace, updateCourseEstimatedCost } = vi.hoisted(() => ({
  logTrace: vi.fn(() => Promise.resolve(undefined)),
  updateCourseEstimatedCost: vi.fn(
    (_courseId: string): Promise<number | undefined> => Promise.resolve(0)
  ),
}));

vi.mock('@/shared/trace-logger', () => ({ logTrace }));
vi.mock('@/services/token-tracking-service', () => ({ updateCourseEstimatedCost }));

vi.mock('@/shared/logger', () => {
  const stub = { debug: vi.fn(), warn: vi.fn(), info: vi.fn(), error: vi.fn() };
  return { logger: stub, default: stub };
});

import {
  calculateImageCostUsd,
  EDIT_REFRESH_DEBOUNCE_MS,
  EDIT_REFRESH_RETRY_DELAY_MS,
  recordImageCallCost,
} from '@/shared/metrics/llm-cost';

const COURSE_ID = '40000000-0000-4000-8000-000000000001';

/**
 * A catalogued image model and the tokens one call reported.
 *
 * Not a hand-supplied `costUsd` any more: an image is priced from
 * `MODEL_CATALOG`'s `image_output` rate like every other call, because the
 * private table that used to hold that number drifted to 6.4x low (mc2-5mhlb).
 */
const IMAGE = { model: 'openai/gpt-5-image-mini', inputTokens: 500, outputTokens: 5_000 };

/** $2.50/1M prompt tokens + $8.00/1M image output tokens. */
const IMAGE_COST_USD = (500 * 2.5) / 1_000_000 + (5_000 * 8) / 1_000_000;

describe('the course total after an image', () => {
  beforeEach(() => {
    vi.useFakeTimers();
    vi.clearAllMocks();
    updateCourseEstimatedCost.mockResolvedValue(0);
  });

  afterEach(async () => {
    updateCourseEstimatedCost.mockResolvedValue(0);
    await vi.advanceTimersByTimeAsync(EDIT_REFRESH_DEBOUNCE_MS + EDIT_REFRESH_RETRY_DELAY_MS * 2);
    vi.useRealTimers();
  });

  it('is re-summed when the image was generated by an edit', async () => {
    await recordImageCallCost(IMAGE, {
      courseId: COURSE_ID,
      stage: 'stage_edit',
      phase: 'inline_block_image',
    });

    // Still debounced, same as a token call: the refresh waits for the rest of
    // the turn rather than running per call.
    expect(updateCourseEstimatedCost).not.toHaveBeenCalled();

    await vi.advanceTimersByTimeAsync(EDIT_REFRESH_DEBOUNCE_MS);

    expect(updateCourseEstimatedCost).toHaveBeenCalledWith(COURSE_ID);
  });

  it('is left to the job when the image came from a pipeline stage', async () => {
    await recordImageCallCost(IMAGE, {
      courseId: COURSE_ID,
      stage: 'stage_7',
      phase: 'stage_7_cover',
    });

    await vi.advanceTimersByTimeAsync(EDIT_REFRESH_DEBOUNCE_MS);

    // Stage 7's factory refreshes once when the job finishes. Refreshing per
    // image would re-read the course's whole trace history per picture.
    expect(updateCourseEstimatedCost).not.toHaveBeenCalled();
  });

  it('records the trace before scheduling the refresh, so the re-sum sees the row', async () => {
    await recordImageCallCost(IMAGE, {
      courseId: COURSE_ID,
      stage: 'stage_edit',
      phase: 'inline_block_image',
    });

    expect(logTrace).toHaveBeenCalledTimes(1);
    expect(logTrace.mock.calls[0][0]).toMatchObject({
      courseId: COURSE_ID,
      stage: 'stage_edit',
      costUsd: IMAGE_COST_USD,
    });
  });

  it('prices the image from the catalogue rather than from a number it was handed', () => {
    expect(calculateImageCostUsd(IMAGE)).toBeCloseTo(IMAGE_COST_USD, 8);
  });

  it('leaves a call it cannot price genuinely unpriced, not zero', () => {
    // An uncatalogued image model used to resolve to a flat $0.04 default, so a
    // routing mistake produced a confident wrong number instead of a hole
    // anybody could see (mc2-5mhlb).
    expect(
      calculateImageCostUsd({ model: 'acme/not-a-model', outputTokens: 5_000 })
    ).toBeUndefined();
    // ...and so does a call whose response reported no tokens at all.
    expect(calculateImageCostUsd({ model: IMAGE.model })).toBeUndefined();
  });

  it('treats a genuine zero-token response as a measurement, not an absence', () => {
    expect(calculateImageCostUsd({ model: IMAGE.model, outputTokens: 0 })).toBe(0);
  });
});
